### ISSUE TITLE
Merge components into one repo?

### ISSUE THREAD

**Issue by emilebosch** [RiotGear/rg#43]
*hides*

It would make contributing slightly easier. Note that home-brew also does it like this with their brew recipes. 

I was using this repository as study material, but now i have to clone each repository individually. Thanks a lot,

Please let me know what you think about this.

**Comment by gregorypratt** [comment]
To be honest I've been thinking about this for quite a while. 

1) Keep the components segregated so people can npm install them
or
2) Have just one repo by bundling them all in one so that the product is easier to contribute new items to.

Both options have their pros and cons. 

I think I might bundle it together and manually break out the tags into their own components rather than the other way around. Best of both worlds?

**Comment by emilebosch** [comment]
@gregorypratt  Thanks for your appreciation. I also think its easier to re-use idioms when its in one repo. I think you should break them up on distribution indeed. Its the best of both worlds! Again thanks so much for making this available!

**Comment by emilebosch** [comment]
If you need any help! Please let me know!

**Comment by gregorypratt** [comment]
It will make it neater when reusing components such as rg-select within others (rg-autocomplete and rg-tags for instance).

I'll crack on with the changes tonight ;-)

**Comment by gregorypratt** [comment]
Done

**Comment by emilebosch** [comment]
Awesome lemme check!
