### ISSUE TITLE
Separate components

### ISSUE THREAD

**Issue by TimWillis** [RiotGear/rg#59]
Instead of downloading a 78kb file I would like to load in components one at a time.

**Comment by gregorypratt** [comment]
If you serve the file from https://cdn.jsdelivr.net/riotgear/2.1.2/rg.min.js it's smaller...

<img width="522" alt="screen shot 2015-11-12 at 14 20 55" src="https://cloud.githubusercontent.com/assets/1453899/11120609/f26c9c32-8948-11e5-849d-46a06a9a419b.png">

**However** this has been a concern of mine as more components are added.

The [plan for RiotGear](http://riotgear.js.org/roadmap/) though is to separate the component's HTML and CSS and produce something more akin to Bootstrap with the components providing the dynamic aspect. That way if you want to use your own JS you can, or if you want to customise the CSS you can.

**Comment by TimWillis** [comment]
Exactly :)

**Comment by gregorypratt** [comment]
**(IMO!) scoping the CSS:**

It's a pain to integrate the tags into your site or if you want to make themes or site wide updates. You end up repeating yourself to override the styles.
We also repeat ourselves across the tags. E.g. any tag with a `.field` class with have to define what a `.field` should look like within each tag.

If however the tags were reliant on a lightweight CSS framework you get small HTML tag files, reusable CSS and aligned styles between your site and our tags. Maximising reuse, maintainability and customisation.

**Separating the tags:**

This could be accomplished, it would need a bit of thought, but we could breakdown the tags so that they can be downloaded separately. They might still need certain things that make downloading the entire library small (the rg utils for instance) but I reckon we could make it more modular.

More thoughts on the subject would be welcome!
