### ISSUE TITLE
use riot.observable API for event handlers

### ISSUE THREAD

**Issue by sylvainpolletvillard** [RiotGear/rg#64]
[Observables](http://riotjs.com/api/observable/) are a core feature of Riot and are very useful for custom events. The advantages compared to callbacks arguments are:
* you can add several distinct listeners
* you can add listeners at different times or different places in the code
* you can use the whole Observable API (off, one...)
* smaller code in tag
* align better with [riot application design](http://riotjs.com/guide/application-design/#observable)

I suggest you replace callback arguments in RiotGear components with events as riot tags are observable by default:

```
this.select = new RgSelect({
  autocomplete: true,
  placeholder: 'Please select a country',
  filterplaceholder: 'Filter countries',
  filteron: 'text',
  options: [{
    text: 'England'
  }, {
    text: 'Scotland'
  }, {
    text: 'Wales'
  }, {
    text: 'Ireland'
  }]
})
.on('open', function () {})
.on('close', function () {})
.on('filter', function () {})
.on('select', function () {})
```

In the component code:
```
this._onopen = opts.onopen

(...)

 get onopen() {
    if (rg.isFunction(this._onopen)) return this._onopen
    return null
  }
  set onopen(onopen) {
    this._onopen = onopen
  }

(...)

 if (this.onopen && !this.isvisible) this.onopen()
```

can be replaced by

```
if(!this.isvisible) this.trigger('open')
```

**Comment by gregorypratt** [comment]
Yeah I did have this at one point during the v2 refactor. My goal (rightly or wrongly in hindsight) was to try and keep the classes as framework agnostic as possible so they could be used elsewhere if required. That's why they inherit from RgTag where the riot stuff sits. *However* how realistic is it that this code will be used elsewhere?! Therefore **I'm happy to refactor the tags to follow this pattern** but I will need to think about versioning and whether I *add* this functionality (v2.2.0) or *replace* the callbacks (v3.0.0). Keeping the callbacks and adding this would create more code, but we'd be making a breaking change for people straight away if we go down the v3 route. Decisions decisions!

**Comment by sylvainpolletvillard** [comment]
Adding this pattern is straight-forward, but of course removing the previous arguments is a breaking change. You may want to deprecate these then remove them for the next major version.

**Comment by gregorypratt** [comment]
Agreed. But I hate adding code, I much prefer deleting it!
